### ISSUE TITLE
Add more datasets

### ISSUE THREAD

**Issue by rangell** [LASER-UMASS/Themis#26]
Add ProPublica crime recidivism dataset (cleaned for our use)
Add NYPD stop-and-frisk dataset (cleaned for our use)

**Comment by brunyuriy** [comment]
@rangell 
Here's a place to look at datasets:
http://fairness-measures.org/Pages/Datasets

There are also datasets here that another study used:
https://github.com/algofairness/fairness-comparison/tree/master/data/raw
